### ISSUE TITLE
Should not run for all repos containing shadow-cljs.edn

### ISSUE THREAD

**Issue by slimslenderslacks** [atomist/atomist-web-sdm#23]
The Push rule here picks up a lot of atomisthq Repos that are not web projects (ie Node skill projects).

I think it would be better to make web-sdm run only for the few projects where it's needed because it's scheduling goals in way too many repos now.

**Comment by slimslenderslacks** [comment]
Instead, could we change line:

https://github.com/atomist/atomist-web-sdm/blob/master/index.ts#L550

to just run only for atomisthq/web-app-cljs?

**Comment by ddgenome** [comment]
Closed by https://github.com/atomist/atomist-web-sdm/commit/bcbf0407e322c6298fb8fd8f612ca26f746a39cb
